apiVersion: v1
kind: Secret
metadata:
  name: shortly-secrets
  namespace: urlshortener
  labels:
    app.kubernetes.io/name: shortly
    app.kubernetes.io/part-of: shortly
    app.kubernetes.io/component: api
type: Opaque
stringData:
  ADMIN_TOKEN: demo-admin-token
