---
kubectl_version: v1.36.5
helm_version: v4.2.2
minikube_version: v1.39.0
tools_enforce_versions: false
k8s_tool_arch_map:
  x86_64: amd64
  aarch64: arm64
k8s_tool_tmp: /tmp
k8s_tool_bin_dir: /usr/local/bin
k8s_tool_completion_dir: /etc/bash_completion.d
